title: Mcgill Sea Ice Group and Ice Ocean Instrumentation Lab (IOIL)
description: Internal Website for brunos sea ice group
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Repository To Edit Website: https://github.com/just-the-docs/just-the-docs-template

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/Slide1.PNG"
